name = "pansou-cf"
main = "src/index.ts"
compatibility_date = "2026-09-07"

# KV 缓存（用户已创建：pansou）
[[kv_namespaces]]
binding = "CACHE"
id = "b53422454d744d0c8af9d10ec92e06b5"

[vars]
ENV = "production"
VERSION = "v0.02"

[observability]
enabled = true